### PR TITLE
#37 Compatibility with Neos 5.0 #43

### PR DESCRIPTION
**Pull request by markuspfeifenberger**
Fixes the output for Neos 5.0

### CODE REVIEW

**Comment by markuspfeifenberger** [comment]
in local development the e2e task run with success

**Comment by Nikdro** [comment]
Any updates here? I would love to see a stable 5.0-compatible version of the package!

**Comment by markuspfeifenberger** [comment]
> Any updates here? I would love to see a stable 5.0-compatible version of the package!

On my local environment the e2e test pass without error - @johannessteu mentioned, that maybe a new testing environment needs to be added for Neos 5!?!

**Comment by johannessteu** [comment]
@markuspfeifenberger can you allow me to push on your branch?

**Pull request merged**
