### PR TITLE
BUGFIX: Only add debug output to html

### PR DESCRIPTION
**Pull request by Sebobo**
Resolves: #57

### CODE REVIEW

**Comment by Sebobo** [comment]
This branch is based upon #119 that's why there is another commit in here

**Comment by Sebobo** [comment]
@johannessteu do you think the supported content types should be configurable?
I'm not sure if there are more than `text/html` that are really compatible.

**Comment by johannessteu** [comment]
Let's start with `text/html` and add a configuration if we need it at some point?

**Review by johannessteu — APPROVED** [review]

**Comment by Sebobo** [comment]
Sadly it doesn't work like this.

The content type of the response is not yet available during the `renderCacheInfoIntoSegment` part.
Therefore it's always `text/html` and not the type set in Fusion.

I think the only way to fix this is to remove the output in a HTTP Component.

**Pull request merged**
